export const PAGES = [
  "/_app.tsx",
  "/_document.tsx",
  "/api/hello.ts",
  "/bar/create",
  "/fuga/confirm/[confirmId]",
  "/fuga/create",
  "/fuga/edit/[someId]",
  "/fuga/new",
  "/hoge/confirm/[id]",
  "/hoge/create",
  "/hoge/edit/[id]",
  "/hoge/new",
  "/",
];
