name: Compare Files

on: [workflow_dispatch]
#   push:
#     branches:
#       - main  # トリガーとなるブランチを設定

jobs:
  compare-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Generate File
        run: node get-page-list.js # ページリストを生成するコマンドを実行

      - name: Compare Files
        run: |
          const { PAGES } = require('./src/constants/page-list');
          const { PAGES: pages2 } = require('./src/constants/page-list');
          console.log({PAGES})
          console.log({pages2})
