name: Update Page List

on: [workflow_dispatch]
#   push:
#     branches:
#       - main  # トリガーとなるブランチを設定

permissions:
  contents: write
  pull-requests: write

jobs:
  compare-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Generate File
        run: node workflow/get-page-list.mjs # ページリストを生成するコマンドを実行

      - name: Prettier format
        run: npx prettier -w page-list.mjs # Prettierでフォーマットしておく

      - name: Compare Files
        id: source
        continue-on-error: true
        run: |
          node workflow/work.mjs # ページリストが同じなら正常終了、違う場合はファイルを置き換え
          result=$?
          echo "$result" >> "${GITHUB_OUTPUT}"

      - name: Branching based on script result
        if: ${{ steps.source.outputs.result == 0 }}
        run: |
          echo "Script returned success!"
          # Add steps for success case, e.g., deploy, notify, etc.

      - name: Handle failure case
        if: ${{ steps.source.outputs.result != 1 }}
        run: |
          echo "Script did not return success."
          # Add steps for failure case, e.g., log error, notify, etc.

      - name: Create PR
        env:
          USERNAME: github-actions[bot]
          EMAIL: github-actions[bot]@users.noreply.github.com
          BRANCH: auto/${{github.run_id}}/${{github.run_attempt}}
          GITHUB_TOKEN: ${{github.token}}
        run: |
          echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
          git switch -c "${BRANCH}"
          git add .
          git commit -m "fix: update page list"
          git push origin "${BRANCH}"
          gh pr create --head "${BRANCH}" --title "update page list/${{github.run_id}}" --body ""
