name: Compare Files

on: [workflow_dispatch]
#   push:
#     branches:
#       - main  # トリガーとなるブランチを設定

jobs:
  compare-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Generate File
        run: node get-page-list.js # ページリストを生成するコマンドを実行

      - name: Compare Files
        run: |
          pwd
          ls -la
          if diff -q page-list.json src/constants/page-list.json; then
            echo "Files are the same"
          else
            echo "Files are different"
            exit 1  # 違う場合はエラーで終了する
          fi
