name: Compare Files

on: [workflow_dispatch]
#   push:
#     branches:
#       - main  # トリガーとなるブランチを設定

jobs:
  compare-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Generate File
        run: node workflow/get-page-list.mjs # ページリストを生成するコマンドを実行

      - name: Prettier format
        run: npx prettier -w page-list.mjs # Prettierでフォーマットしておく 

      - name: Compare Files
        run: node workflow/work.mjs # ページリストが同じなら正常終了、違う場合はファイルを置き換え
